### ISSUE TITLE
Help please there is getting an error of 'java.util.ConcurrentModificationException' and the  Rider App Crashes when loadAllAvailableDriver method is called

### ISSUE THREAD

**Issue by reda-moumen** [IramML/UberClone#11]
Hello, I'd like to thank you first for the great job you did, and for making it open source you helped us so much in our study project. On the other hand, many users of your app are getting the error of **### 'java.util.ConcurrentModificationException'** and **the  Rider App Crashes when loadAllAvailableDriver method is called** :

java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.iramml.uberclone.riderapp.Activities.Home.loadAllAvailableDriver(Home.java:710)
        at com.iramml.uberclone.riderapp.Activities.Home.access$500(Home.java:115)
        at com.iramml.uberclone.riderapp.Activities.Home$22.onDataChange(Home.java:690)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@19.3.0:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@19.3.0:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@19.3.0:55)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by IramML** [comment]
I'm going to check this today, I'm going to take the opportunity to migrate to androidx this project

**Comment by IramML** [comment]
This bug is already fixed on this new [commit](https://github.com/IramML/UberClone/commit/fe30a872dddd8d58ea914eb4fc01e30f1cf8a497)
