### ISSUE TITLE
DriverApp crash when pickup request find a driver and make a call

### ISSUE THREAD

**Issue by EowynnAR** [IramML/UberClone#15]
Buenas Iram, estoy empezando con este proyecto y me gusta mucho lo que hiciste, pero estoy teniendo varios errores, y este es uno, si me podrías ayudar.
Cuando el cliente encuentra un conductor y realiza el llamado la app del driver crashea cuando aparece la ventana para aceptar el viaje, dejo el log

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iramml.uberclone.driverapp, PID: 5504
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        ----->at com.iramml.uberclone.driverapp.Activities.CustommerCall$4.onResponse(CustommerCall.java:120)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Estoy atento a su respuesta.
Muchas gracias.

**Comment by IramML** [comment]
Tienes activada la API de rutas? Con billing, gratuita no

**Comment by EowynnAR** [comment]
Ya lo solucione, estaba activada pero la api key estaba mal, ahora funciona
perfecto, voy a continuar con las pruebas. Está bien si te escribo por acá?
Me parece muy invasivo.
Saludos y muchas gracias!

**Comment by IramML** [comment]
Claro, por donde gustes
