### ISSUE TITLE
Rider App Crashes when loadAllAvailableDriver method is called

### ISSUE THREAD

**Issue by Emml-Anim** [IramML/UberClone#9]
Please help me out with this error. my Logcat is below

2020-04-16 14:44:41.694 6541-6541/com.iramml.uberclone.riderapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iramml.uberclone.riderapp, PID: 6541
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.iramml.uberclone.riderapp.Activities.Home.loadAllAvailableDriver(Home.java:709)
        at com.iramml.uberclone.riderapp.Activities.Home.displayLocation(Home.java:700)
        at com.iramml.uberclone.riderapp.Activities.Home.access$200(Home.java:116)
        at com.iramml.uberclone.riderapp.Activities.Home$1.locationResponse(Home.java:170)
        at com.iramml.uberclone.riderapp.Util.Location$1.onLocationResult(Location.java:37)
        at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
        at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
        at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by rdmn** [comment]
I have the same problem :/

**Comment by IramML** [comment]
This issue is already fixed on this new [commit](https://github.com/IramML/UberClone/commit/fe30a872dddd8d58ea914eb4fc01e30f1cf8a497)
